import fs from 'node:fs';
import {hash} from './records/store.mjs';
import {fileContext} from './context.mjs';
import {Domains} from './domains.mjs';
import {visibleRows} from './visibility.mjs';
export const procedureKinds=['health-summary','portfolio','connection-check','selftest','job-check','disk-check','brief-review','conversation-review','attention-review','lead','radar','memory-capture','domain-watch','spend-guard','board-export','browser-post'];
export async function procedure(job,{store,query,provider}){
  const kind=job.kind;let result;
  if(kind==='health-summary'){
    const recent=query.rows('health_observations').filter(r=>Date.parse(r.observed_at||r.created_at)>=Date.now()-7*86400000),episodes=query.rows('health_episodes').filter(r=>Date.parse(r.onset_at||r.created_at)>=Date.now()-30*86400000),medication=query.rows('medications').filter(r=>Date.parse(r.taken_at||r.created_at)>=Date.now()-30*86400000);
    const timezone=query.rows('profiles')[0]?.timezone||'UTC',day=d=>new Intl.DateTimeFormat('en-CA',{timeZone:timezone}).format(new Date(d));result={observations:recent,headaches_last_30_days:episodes.filter(e=>!e.cancelled_at).length,medication_days_last_30_days:new Set(medication.map(m=>day(m.taken_at||m.created_at))).size,no_recent_measurements:!recent.length};
  }else if(kind==='disk-check'){const stat=fs.statfsSync(store.root);result={free_bytes:Number(stat.bavail)*Number(stat.bsize),total_bytes:Number(stat.blocks)*Number(stat.bsize),needs_attention:Number(stat.bavail)/Number(stat.blocks)<0.2};}
  else if(['selftest','job-check'].includes(kind)){store.scan();result={problems:store.problems,failed:query.rows('job_receipts').filter(r=>r.state!=='verified'),overdue:query.rows('jobs').filter(j=>!j.paused&&Date.parse(j.next_run)<Date.now()-3600000)};}
  else if(kind==='portfolio'||kind==='watch'||kind==='domain-watch'){
    const topics=kind==='portfolio'?query.rows('collections').filter(c=>c.name==='Links').flatMap(c=>query.rows('collection_items').filter(i=>i.collection_id===c.id).map(i=>({id:i.id,url:i.data.url}))):query.rows('watch_topics');result=[];
    for(const topic of topics)for(const raw of topic.urls||topic.url?[...(topic.urls||[topic.url])]:[]){const url=new URL(raw);if(url.protocol!=='https:')throw new Error('Public sources need HTTPS');try{const response=await fetch(url,{signal:AbortSignal.timeout(15000)}),text=(await response.text()).slice(0,100000),digest=hash(text),old=query.rows('watch_observations').filter(o=>o.topic_id===topic.id&&o.url===raw).at(-1);const observation=store.save('watch_observations',{topic_id:topic.id,url:raw,status:response.status,content:text,observed_at:new Date().toISOString(),sha256:digest,changed:!!old&&old.sha256!==digest});result.push({id:observation.id,url:raw,ok:response.ok,changed:observation.changed});}catch(e){result.push({url:raw,ok:false,error:'Source read did not finish'});}}
  }else if(kind==='profiling'){
    const domains=new Domains(query,{provider});const results=[];for(const note of visibleRows(query,'notes'))results.push(await domains.invoke('process-note',{note_id:note.id}));return {verified:true,review_items:results.reduce((n,r)=>n+r.processed,0),delivery:'notebook'};
  }else if(kind==='connection-check'){result=[];const folder=store.state+'/connectors';if(fs.existsSync(folder))for(const filename of fs.readdirSync(folder).filter(f=>f.endsWith('.json'))){const config=JSON.parse(fs.readFileSync(folder+'/'+filename)),url=config.test_url||(filename==='gdrive.json'?new URL('/drive/v3/about?fields=user',config.origin):new URL(config.route||'/',config.origin));try{const response=await fetch(url,{headers:config.token?{Authorization:'Bearer '+config.token}:{},signal:AbortSignal.timeout(15000)});result.push({connector:filename.replace('.json',''),ok:response.ok,status:response.status});}catch{result.push({connector:filename.replace('.json',''),ok:false,error:'Connection read failed'});}}}
  else if(kind==='attention-review'){result={deadlines:query.rows('deadlines').filter(d=>d.status!=='closed'&&Date.parse(d.due_at)-Date.now()<3*86400000),approvals:query.rows('approvals').filter(a=>a.status==='pending'),work:query.rows('work_items').filter(w=>w.state==='awaiting_approval'||w.state==='verified')};}
  else if(['spend-guard','board-export','browser-post'].includes(kind))result=await new Domains(query,{provider}).invoke('run-connector',{name:kind,payload:job.payload,approval_id:job.approval_id});
  else{
    if(!provider)throw new Error('Configure an assistant for this routine');
    const contracts={'brief-review':'Critique the most recent saved brief against its actual sources, voice rules and prior deliveries. Return concrete unsupported claims or a clear pass. Do not send a replacement.','conversation-review':'Check whether the most recent saved delivered message is present in conversation history. Quote only actual saved text.','lead':'Prepare one clear relatable post or reply using recent original work and verified source observations. Never invent personal experiences. Do not publish. If none is ready, save the reason.','radar':'Compare the newest recorded source observations with the goals. Prepare at most one proposal with evidence, cost and reversible trial.','memory-capture':'Review explicitly supplied conversations and propose source-quoted lasting facts for review. Never sweep unrelated account files.'};
    result=await provider({kind,context:{...fileContext(store),sources:query.rows('watch_observations').slice(-20),notes:visibleRows(query,'notes'),goals:query.rows('goals')},contract:contracts[kind]||'Use the supplied records and preserve uncertainty. No outward actions.'});
  }
  const silent=['portfolio','watch','domain-watch'].includes(kind)&&Array.isArray(result)&&!result.some(r=>r.changed||!r.ok);
  const record=store.save('notes',{title:job.title||kind,content:typeof result==='string'?result:JSON.stringify(result,null,2),source_app:kind,job_id:job.id});return {verified:true,record_id:record.id,content_hash:store.get('notes',record.id)._hash,delivery:'notebook',silent};
}
