import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import ReactMarkdown from 'react-markdown';
import {ApiKeysManager} from '@/components/settings/ApiKeysManager';
import {AISuggestionPreferences} from '@/components/settings/AISuggestionPreferences';
import {AiVisibilitySettings} from '@/components/settings/AiVisibilitySettings';
import {NotificationPreferences} from '@/components/settings/NotificationPreferences';
import {Link} from 'react-router-dom';
import {Button} from '@/components/ui/button';
import {Download} from 'lucide-react';
import {PersonalControl} from './PersonalControl';
async function call(route:string,body?:any){const r=await fetch('/api/'+route,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw new Error(data.error);return data;}
export default function Control(){
  const qc=useQueryClient(),[goal,setGoal]=useState(''),[timezone,setTimezone]=useState(Intl.DateTimeFormat().resolvedOptions().timeZone),[error,setError]=useState(''),[search,setSearch]=useState('');
  const [url,setUrl]=useState('https://api.openai.com/v1/chat/completions'),[key,setKey]=useState(''),[model,setModel]=useState(''),[remote,setRemote]=useState(''),[routine,setRoutine]=useState('coaching'),[hours,setHours]=useState('1440'),[origin,setOrigin]=useState(''),[pairCode,setPairCode]=useState(''),[createdCode,setCreatedCode]=useState(''),[offline,setOffline]=useState('all');
  const conflicts=useQuery({queryKey:['saved-conflicts'],queryFn:()=>call('conflicts'),refetchInterval:5000});
  const [connector,setConnector]=useState('spend-guard'),[connectorUrl,setConnectorUrl]=useState(''),[connectorKey,setConnectorKey]=useState(''),[threshold,setThreshold]=useState('10'),[valuePath,setValuePath]=useState('balance'),[driveKey,setDriveKey]=useState(''),[driveFolder,setDriveFolder]=useState('');
  const {data}=useQuery({queryKey:['candidate-status'],queryFn:()=>call('status'),refetchInterval:5000});
  const backups=useQuery({queryKey:['saved-backups'],queryFn:()=>call('backups'),refetchInterval:10000});
  const [backupId,setBackupId]=useState(''),[recovery,setRecovery]=useState<any>(null),[restoring,setRestoring]=useState(false);
  const usefulWork=useQuery({queryKey:['latest-goal-work'],queryFn:()=>call('latest-work'),refetchInterval:5000});
  const results=useQuery({queryKey:['candidate-search',search],queryFn:()=>call('search?q='+encodeURIComponent(search)),enabled:!!search});
  const action=async(route:string,body:any)=>{try{setError('');await call(route,body);qc.invalidateQueries();}catch(e:any){setError(e.message);}};
  return <div className="max-w-4xl space-y-6"><h1 className="text-2xl font-bold">Settings</h1><p>Manage your notebook, assistant and connected devices.</p>
    <p role="alert" className="text-red-400">{error}</p>
    <Button asChild className="min-h-11 gap-2"><Link to="/dashboard/settings/import"><Download className="h-4 w-4" aria-hidden="true"/>Import from Menerio</Link></Button>
    {usefulWork.data?.data[0]&&<section className="border rounded p-4"><h2 className="text-xl">Your latest work result</h2><p>{usefulWork.data.verification_current?'Checked against its task.':'This result has changed since its check.'}</p><div className="prose dark:prose-invert max-w-none"><ReactMarkdown>{usefulWork.data.data[0].content}</ReactMarkdown></div><a className="underline" href={'/dashboard/notes/'+usefulWork.data.data[0].id}>Open the saved note</a></section>}
    <details className="border rounded p-4"><summary>Privacy, suggestions and notifications</summary><AiVisibilitySettings/><AISuggestionPreferences/><NotificationPreferences/></details>
    <details className="border rounded p-4"><summary>Connect other assistants</summary><ApiKeysManager/></details>
    <button className="border rounded p-2" onClick={()=>action('assistant/open',{})}>Open the Windows assistant</button>
    <details className="border rounded p-4"><summary>Routine delivery</summary><p>Keep results in the notebook, or deliver them to the owner of your separately configured test Telegram bot. Uncertain sends pause for review.</p><button className="border p-2" onClick={()=>action('delivery',{delivery:'notebook'})}>Keep results here</button><button className="border p-2" onClick={()=>action('delivery',{delivery:'telegram'})}>Use the test Telegram chat</button></details>
    <details className="border rounded p-4"><summary>Optional account connections</summary><p>Credentials stay on this device. Configure a connection on the device that owns its routine. Posting also requires approval of the exact payload.</p><form className="space-y-3" onSubmit={e=>{e.preventDefault();action('functions/configure-connector',{name:connector,url:connectorUrl,token:connectorKey,threshold:Number(threshold),value_path:valuePath}).then(()=>setConnectorKey(''));}}><label>Connection<select className="block bg-background border p-2" value={connector} onChange={e=>setConnector(e.target.value)}><option>spend-guard</option><option>board-export</option><option>browser-post</option></select></label><label>Service address<input required className="block w-full bg-background border p-2" value={connectorUrl} onChange={e=>setConnectorUrl(e.target.value)}/></label><label>Service token<input type="password" autoComplete="off" className="block bg-background border p-2" value={connectorKey} onChange={e=>setConnectorKey(e.target.value)}/></label><label>Balance field<input className="block bg-background border p-2" value={valuePath} onChange={e=>setValuePath(e.target.value)}/></label><label>Notify below<input type="number" className="block bg-background border p-2" value={threshold} onChange={e=>setThreshold(e.target.value)}/></label><button className="border p-2">Save connection</button></form><form className="space-y-3 mt-6" onSubmit={e=>{e.preventDefault();action('functions/gdrive-proxy',{action:'configure',access_token:driveKey,folder_id:driveFolder}).then(()=>setDriveKey(''));}}><h2>Read a Google Drive folder</h2><label>Read-only access token<input type="password" autoComplete="off" required className="block bg-background border p-2" value={driveKey} onChange={e=>setDriveKey(e.target.value)}/></label><label>Folder ID<input required className="block bg-background border p-2" value={driveFolder} onChange={e=>setDriveFolder(e.target.value)}/></label><button className="border p-2">Test and connect Drive</button></form><button className="border p-2 mt-3" onClick={()=>action('functions/gdrive-sync',{})}>Import the connected folder</button></details>
    <details className="border rounded p-4"><summary>Pair the server and media</summary>{data?.device==='vps'?<><button className="border p-2" onClick={async()=>{try{setCreatedCode((await call('pair/create',{})).code);}catch(e:any){setError(e.message);}}}>Create a five minute pairing code</button><p>{createdCode}</p></>:<form className="space-y-3" onSubmit={e=>{e.preventDefault();action('pair/connect',{origin,code:pairCode});}}><label>Server address<input className="block w-full bg-background border p-2" value={origin} onChange={e=>setOrigin(e.target.value)} required/></label><label>Pairing code<input className="block w-full bg-background border p-2" value={pairCode} onChange={e=>setPairCode(e.target.value)} required/></label><button className="border p-2">Pair this computer</button></form>}<p>Pairing gives the VPS schedule ownership. Private Git sync connects the knowledge files separately.</p><label>Offline media<select className="bg-background border p-2" value={offline} onChange={e=>setOffline(e.target.value)}><option value="all">Keep all media</option><option value="selected">Keep downloaded media only</option></select></label><button className="border p-2" onClick={()=>action('media/offline',{offline,selected:[]})}>Save offline choice</button><button className="border p-2" onClick={()=>action('media/sync',{})}>Transfer media now</button><p>Media transfer: {data?.mediaSync?.state||'Not paired'}</p></details>
    <details className="border rounded p-4"><summary>Connect your assistant</summary><form className="space-y-3" onSubmit={e=>{e.preventDefault();action('provider',{url,key,model}).then(()=>setKey(''));}}><p>Your key stays on this device, outside synced records. Choose a provider and model you use.</p><label className="block">Model endpoint<input className="block w-full border bg-background p-2" value={url} onChange={e=>setUrl(e.target.value)} required/></label><label className="block">Model name<input className="block border bg-background p-2" value={model} onChange={e=>setModel(e.target.value)} required/></label><label className="block">API key<input type="password" autoComplete="off" className="block border bg-background p-2" value={key} onChange={e=>setKey(e.target.value)} required/></label><button className="border p-2">Test and connect</button></form></details>
    {!data?.goalSetupComplete&&<form className="space-y-3 border rounded p-4" onSubmit={e=>{e.preventDefault();action('setup',{goal,timezone,delivery:'notebook'});}}><h2>Start with one goal</h2><label className="block">What matters to you?<input className="block w-full bg-background border rounded p-2" value={goal} onChange={e=>setGoal(e.target.value)} required/></label><label className="block">Timezone<input className="block bg-background border rounded p-2" value={timezone} onChange={e=>setTimezone(e.target.value)} required/></label><button className="border rounded p-2">Start</button></form>}
    <PersonalControl/>
    <section><h2 className="text-xl">Find your knowledge</h2><input aria-label="Search all records" className="bg-background border rounded p-2" value={search} onChange={e=>setSearch(e.target.value)}/><ul>{results.data?.data.map((r:any)=><li key={r.uid}>{r.title} ({r.type})</li>)}</ul></section>
    <section><h2 className="text-xl">Routines</h2><p>Schedule owner: {data?.owner||'Not configured'}. Assistant: {data?.runtimeConfigured?'available':'not configured'}. Account access is checked when work runs.</p><button className="border p-2 rounded" onClick={()=>action('jobs/run',{})}>Run due routines</button><ul>{data?.schedules.map((j:any)=><li className="border-b py-3 flex flex-wrap gap-4" key={j.id}><span>{j.kind}: {j.state}. Next: {j.next_run}</span><button onClick={()=>action('jobs/update',{id:j.id,paused:!j.paused})}>{j.paused?'Resume':'Pause'}</button>{j.last_outcome&&<span>{j.last_outcome}</span>}</li>)}</ul></section>
    {data?.configured&&<form className="flex gap-3 flex-wrap" onSubmit={e=>{e.preventDefault();action('jobs/add',{kind:routine,interval_ms:Number(hours)*60000});}}><label>Routine<select className="bg-background border p-2" value={routine} onChange={e=>setRoutine(e.target.value)}>{data?.kinds.map((kind:string)=><option key={kind}>{kind}</option>)}</select></label><label>Minutes between runs<input type="number" min="1" className="bg-background border p-2 w-20" value={hours} onChange={e=>setHours(e.target.value)}/></label><button className="border p-2">Enable routine</button></form>}
    <details className="border rounded p-4"><summary>Sync and schedule ownership</summary><form className="space-y-3" onSubmit={e=>{e.preventDefault();action('sync/configure',{url:remote});}}><label>Private GitHub repository<input className="block w-full bg-background border p-2" value={remote} onChange={e=>setRemote(e.target.value)} required/></label><p>The installed Git credential manager signs in. Records sync every minute. Keys, media and search databases stay outside Git.</p><button className="border p-2">Connect record sync</button></form><p>Sync: {data?.sync?.state||'Not connected'}</p><button className="border p-2" onClick={()=>action('sync/run',{})}>Sync now</button><p>Choose one schedule owner. Choosing VPS keeps this computer quiet while offline.</p><button className="border p-2" onClick={()=>action('owner',{owner:'vps'})}>VPS owns schedules</button><button className="border p-2 ml-3" onClick={()=>action('owner',{owner:'local'})}>This computer owns schedules</button></details>
    <section><h2 className="text-xl">Review conflicting edits</h2>{conflicts.data?.data.map((c:any)=><article className="border p-4 my-3" key={c.id}><h3>{c.path||c.type+'/'+c.record_id}</h3><div className="grid md:grid-cols-2 gap-3">{['local','remote'].map(choice=><div key={choice}><h4>{choice==='local'?'Your pending edit':'The saved edit'}</h4><pre className="whitespace-pre-wrap max-h-64 overflow-auto text-xs">{c.encoding==='base64'?'This copy of the file is saved for recovery.':typeof c[choice]==='string'?c[choice]:JSON.stringify(c[choice],null,2)}</pre><button className="border p-2" onClick={()=>action('conflicts/resolve',{id:c.id,choice})}>Keep this version</button></div>)}</div></article>)}</section>
    <section><h2 className="text-xl">Recovery</h2><p>Last file scan: {data?.lastScan}. Last search rebuild: {data?.lastIndex}.</p><button className="border p-2 rounded" onClick={()=>action('index/rebuild',{})}>Rebuild search</button><button className="border p-2 rounded ml-3" onClick={()=>action('backup',{})}>Save a backup</button><form className="space-y-2 mt-3" onSubmit={async e=>{e.preventDefault();setRestoring(true);setRecovery(null);try{setError('');setRecovery(await call('restore-copy',{backup_id:backupId}));}catch(error:any){setError(error.message);}finally{setRestoring(false);}}}><label>Saved backup<select required className="block border bg-background p-2" value={backupId} onChange={e=>setBackupId(e.target.value)}><option value="">Choose a backup</option>{backups.data?.data.map((b:any)=><option key={b.id} value={b.id}>{new Date(b.at).toLocaleString()} ({b.records} records)</option>)}</select></label><p>Restore into empty, separate storage and compare saved content and media. The restored copy is retained for recovery.</p><button disabled={restoring} className="border p-2">{restoring?'Checking the restored copy...':'Restore a separate copy'}</button></form>{recovery&&<div role="status"><p>Restored and checked {recovery.records} records and {recovery.compared_files} files. Search was rebuilt.</p><p>Restored folder: {recovery.workspace}</p>{recovery.excluded_files.length>0&&<p>{recovery.excluded_files.length} files outside the saved knowledge contract were excluded.</p>}</div>}<ul>{data?.problems.map((p:any,i:number)=><li key={i}>{p.error}: {p.record||p.file}</li>)}</ul><p>Conflicts waiting for review: {data?.conflicts.length||0}</p></section>
    <p className="text-sm text-muted-foreground">Lexicon and note graph are deferred. Provider-based analysis requires your chosen assistant. Outward actions wait for specific permission.</p>
  </div>;
}
