import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
async function call(route:string,body?:any){const r=await fetch('/api/'+route,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw new Error(data.error);return data;}
export default function Control(){
  const qc=useQueryClient(),[goal,setGoal]=useState(''),[timezone,setTimezone]=useState(Intl.DateTimeFormat().resolvedOptions().timeZone),[error,setError]=useState(''),[search,setSearch]=useState('');
  const [url,setUrl]=useState('https://api.openai.com/v1/chat/completions'),[key,setKey]=useState(''),[model,setModel]=useState(''),[remote,setRemote]=useState(''),[routine,setRoutine]=useState('coaching'),[hours,setHours]=useState('24');
  const conflicts=useQuery({queryKey:['saved-conflicts'],queryFn:()=>call('conflicts'),refetchInterval:5000});
  const {data}=useQuery({queryKey:['candidate-status'],queryFn:()=>call('status'),refetchInterval:5000});
  const results=useQuery({queryKey:['candidate-search',search],queryFn:()=>call('search?q='+encodeURIComponent(search)),enabled:!!search});
  const action=async(route:string,body:any)=>{try{setError('');await call(route,body);qc.invalidateQueries();}catch(e:any){setError(e.message);}};
  return <div className="max-w-4xl space-y-6"><h1 className="text-2xl font-bold">Your control desk</h1><p>Knowledge stays in your files. This candidate uses a separate workspace.</p>
    <p role="alert" className="text-red-400">{error}</p>
    <details className="border rounded p-4"><summary>Connect your assistant</summary><form className="space-y-3" onSubmit={e=>{e.preventDefault();action('provider',{url,key,model}).then(()=>setKey(''));}}><p>Your key stays on this device, outside synced records. Choose a provider and model you use.</p><label className="block">Model endpoint<input className="block w-full border bg-background p-2" value={url} onChange={e=>setUrl(e.target.value)} required/></label><label className="block">Model name<input className="block border bg-background p-2" value={model} onChange={e=>setModel(e.target.value)} required/></label><label className="block">API key<input type="password" autoComplete="off" className="block border bg-background p-2" value={key} onChange={e=>setKey(e.target.value)} required/></label><button className="border p-2">Test and connect</button></form></details>
    {!data?.configured&&<form className="space-y-3 border rounded p-4" onSubmit={e=>{e.preventDefault();action('setup',{goal,timezone,delivery:'notebook'});}}><h2>Start with one goal</h2><label className="block">What matters to you?<input className="block w-full bg-background border rounded p-2" value={goal} onChange={e=>setGoal(e.target.value)} required/></label><label className="block">Timezone<input className="block bg-background border rounded p-2" value={timezone} onChange={e=>setTimezone(e.target.value)} required/></label><button className="border rounded p-2">Start</button></form>}
    <section><h2 className="text-xl">Find your knowledge</h2><input aria-label="Search all records" className="bg-background border rounded p-2" value={search} onChange={e=>setSearch(e.target.value)}/><ul>{results.data?.data.map((r:any)=><li key={r.uid}>{r.title} ({r.type})</li>)}</ul></section>
    <section><h2 className="text-xl">Routines</h2><p>Schedule owner: {data?.owner||'Not configured'}. Provider: {data?.runtimeConfigured?'connected':'not connected'}.</p><button className="border p-2 rounded" onClick={()=>action('jobs/run',{})}>Run due routines</button><ul>{data?.schedules.map((j:any)=><li className="border-b py-3 flex flex-wrap gap-4" key={j.id}><span>{j.kind}: {j.state}. Next: {j.next_run}</span><button onClick={()=>action('jobs/update',{id:j.id,paused:!j.paused})}>{j.paused?'Resume':'Pause'}</button>{j.last_outcome&&<span>{j.last_outcome}</span>}</li>)}</ul></section>
    {data?.configured&&<form className="flex gap-3 flex-wrap" onSubmit={e=>{e.preventDefault();action('jobs/add',{kind:routine,interval_ms:Number(hours)*3600000});}}><label>Routine<select className="bg-background border p-2" value={routine} onChange={e=>setRoutine(e.target.value)}>{data?.kinds.map((kind:string)=><option key={kind}>{kind}</option>)}</select></label><label>Hours between runs<input type="number" min="1" className="bg-background border p-2 w-20" value={hours} onChange={e=>setHours(e.target.value)}/></label><button className="border p-2">Enable routine</button></form>}
    <details className="border rounded p-4"><summary>Sync and schedule ownership</summary><form className="space-y-3" onSubmit={e=>{e.preventDefault();action('sync/configure',{url:remote});}}><label>Private GitHub repository<input className="block w-full bg-background border p-2" value={remote} onChange={e=>setRemote(e.target.value)} required/></label><p>The installed Git credential manager signs in. Records sync every minute. Keys, media and search databases stay outside Git.</p><button className="border p-2">Connect record sync</button></form><p>Sync: {data?.sync?.state||'Not connected'}</p><button className="border p-2" onClick={()=>action('sync/run',{})}>Sync now</button><p>Choose one schedule owner. Choosing VPS keeps this computer quiet while offline.</p><button className="border p-2" onClick={()=>action('owner',{owner:'vps'})}>VPS owns schedules</button><button className="border p-2 ml-3" onClick={()=>action('owner',{owner:'local'})}>This computer owns schedules</button></details>
    <section><h2 className="text-xl">Review conflicting edits</h2>{conflicts.data?.data.map((c:any)=><article className="border p-4 my-3" key={c.id}><h3>{c.path||c.type+'/'+c.record_id}</h3><div className="grid md:grid-cols-2 gap-3">{['local','remote'].map(choice=><div key={choice}><h4>{choice==='local'?'Your pending edit':'The saved edit'}</h4><pre className="whitespace-pre-wrap max-h-64 overflow-auto text-xs">{typeof c[choice]==='string'?c[choice]:JSON.stringify(c[choice],null,2)}</pre><button className="border p-2" onClick={()=>action('conflicts/resolve',{id:c.id,choice})}>Keep this version</button></div>)}</div></article>)}</section>
    <section><h2 className="text-xl">Recovery</h2><p>Last file scan: {data?.lastScan}. Last search rebuild: {data?.lastIndex}.</p><button className="border p-2 rounded" onClick={()=>action('index/rebuild',{})}>Rebuild search</button><button className="border p-2 rounded ml-3" onClick={()=>action('backup',{})}>Save a backup</button><ul>{data?.problems.map((p:any,i:number)=><li key={i}>{p.error}: {p.record||p.file}</li>)}</ul><p>Conflicts waiting for review: {data?.conflicts.length||0}</p></section>
    <p className="text-sm text-muted-foreground">Lexicon and note graph are deferred. Provider-based analysis requires your chosen assistant. Outward actions wait for specific permission.</p>
  </div>;
}
