import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import http from 'node:http';
import {Store} from '../core/records/store.mjs';import {QueryService} from '../core/query.mjs';import {lead} from '../core/lead.mjs';import {leadCommand} from '../core/lead-commands.mjs';import {validateReach} from '../core/lead-reach.mjs';
// Its sources are local fixture servers, which the product itself refuses to read (core/outbound-fetch.mjs).
process.env.GODSPEED_OUTBOUND_ALLOW_LOCAL='1';
function fixture(){const store=new Store(fs.mkdtempSync(path.join(os.tmpdir(),'godspeed-market-reach-'))),query=new QueryService(store),goal=store.save('goals',{title:'Fictional useful public work',status:'adopted'}),position=store.save('lead_positions',{title:'Fictional retained evidence',status:'adopted',goal_id:goal.id}),offer=store.save('notes',{title:'Fictional checklist',content:'A fictional dated-source checklist is available.',lead_evidence:true});store.save('lead_examples',{status:'approved',content:'An old answer deserves a new date.'});return {store,query,position,offer};}
function entry(f){return {kind:'entry',title:'Fictional source-aware contribution',position_id:f.position.id,shape:'post',options:[{text:'A source date helps you question an old answer.',lighthearted:false},{text:'My fictional checklist puts an expiry date on confident guesses.',lighthearted:true},{text:'Keep the date beside the fact you intend to reuse.',lighthearted:false}],evidence:[{source_id:f.offer.id,quote:f.offer.content}],reader_check:{reader:'People reading saved notes',venue:'A public conversation',understands:'Dates distinguish old claims',feels:'Curious',takeaway:'Check the source date',spam_check:'Offers one useful idea'},reach:null};}
async function server(t,content){let calls=[];const srv=http.createServer((req,res)=>{calls.push({method:req.method,path:req.url});res.end(content(req));});await new Promise(r=>srv.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>srv.close(r)));return {url:'http://127.0.0.1:'+srv.address().port,calls};}
test('market sources rotate independently by fifteen and repeat the same selection on one day',async t=>{
 const f=fixture(),web=await server(t,req=>'Fictional market evidence '+req.url);for(let n=0;n<17;n++)leadCommand(f,['market',JSON.stringify({name:'Fictional market '+n,url:web.url+'/'+n})]);let selections=[];
 const provider=async input=>{selections.push(input.context.market.map(m=>m.id));assert.equal(input.context.sources.length,15);assert.ok(input.context.sources.every(s=>s.market_id&&s.content.includes('Fictional market evidence')));return {kind:'quiet',reason:'The actually read market sources contain no useful new opening'};};
 await lead({id:'fictional-market'}, {...f,provider});await lead({id:'fictional-market'}, {...f,provider});assert.deepEqual(selections[0],selections[1]);for(const r of f.store.list('lead_runs'))f.store.save('lead_runs',{id:r.id,local_day:'2026-01-01'});await lead({id:'fictional-market'}, {...f,provider});assert.notDeepEqual(selections[1],selections[2]);assert.equal(web.calls.length,45);assert.equal(f.store.list('notifications').length,0);assert.equal(f.store.list('watch_observations').length,45);assert.ok(f.store.list('lead_runs').every(r=>r.market_ids.length===15));
});
test('one real source-checked reach remains part of one local draft, and no send occurs',async t=>{
 const f=fixture(),date=new Date().toISOString().slice(0,10),statement=date+' Fictional question: how can I retain the date of a source?',web=await server(t,()=>statement);leadCommand(f,['contact',JSON.stringify({name:'Fictional reader',url:web.url+'/statement'})]);const contact=f.store.list('lead_contacts')[0];let checked=false;
 const result=await lead({id:'fictional-reach'},{...f,provider:async input=>{if(input.kind==='lead-verification'){checked=true;assert.equal(input.context.draft.reach.state,'draft');assert.equal(input.context.draft.reach.url,web.url+'/statement');return {passed:true,reason:'Fictional dated statement and actual available checklist match'};}return {...entry(f),reach:{contact_id:contact.id,source_id:input.context.sources[0].id,quote:statement,statement_date:date,date_quote:date,offer_source_id:f.offer.id,offer_quote:f.offer.content,why_them:'The actual dated question asks for source dates',offer:'A dated-source checklist',draft:'I have a fictional dated-source checklist that may help you keep the source date beside each claim.'}};}});
 assert.equal(checked,true);assert.equal(f.store.list('lead_entries').length,1);assert.equal(f.store.list('notifications').length,1);assert.ok(f.store.get('notes',result.record_id).content.includes('Draft for Fictional reader'));assert.equal(f.store.get('lead_entries',result.entry_id).reach.state,'draft');assert.ok(web.calls.every(c=>c.method==='GET'));assert.equal(web.calls.length,1);
});
test('reach refuses missing dates, stale statements, invented quotes and unsupported personal relationships',()=>{
 const date=new Date().toISOString().slice(0,10),contact={id:'person',name:'Fictional reader'},source={id:'source',contact_id:'person',url:'https://example.invalid/statement',content:date+' Question'},offer={id:'offer',content:'Fictional offered checklist'},context={contacts:[contact],sources:[source],local:[offer],notes:[]},reach={contact_id:'person',source_id:'source',quote:'Question',statement_date:date,date_quote:date,offer_source_id:'offer',offer_quote:offer.content,why_them:'An actual question',offer:'A checklist',draft:'This fictional checklist may help.'};
 assert.equal(validateReach(reach,context).state,'draft');assert.throws(()=>validateReach({...reach,quote:'Invented'},context),/actual sources/);assert.throws(()=>validateReach({...reach,date_quote:'unknown'},context),/actual sources/);assert.throws(()=>validateReach(reach,{...context,now:Date.now()+16*86400000}),/recent dated/);assert.throws(()=>validateReach(reach,{...context,contacts:[{...contact,known_person:true,relationship_confirmed:true,relationship:'Fictional colleague',shared_event_note_id:'missing'}]}),/not confirmed/);
});
test('contact edits cannot silently discard a confirmed relationship or update a hidden record',()=>{
 const f=fixture(),event=f.store.save('notes',{title:'Fictional shared event',content:'A fictional meeting happened.'});assert.throws(()=>leadCommand(f,['contact',JSON.stringify({name:'Fictional reader',url:'https://example.invalid/reader',known_person:true,relationship_confirmed:'yes',relationship:'Fictional colleague',shared_event_note_id:event.id})]),/confirmed relationship/);
 leadCommand(f,['contact',JSON.stringify({name:'Fictional reader',url:'https://example.invalid/reader',known_person:true,relationship_confirmed:true,relationship:'Fictional colleague',shared_event_note_id:event.id})]);const c=f.store.list('lead_contacts')[0];leadCommand(f,['contact',JSON.stringify({id:c.id,name:c.name,url:c.url,hot:true})]);assert.equal(f.store.get('lead_contacts',c.id).known_person,true);assert.equal(f.store.get('lead_contacts',c.id).shared_event_note_id,event.id);f.store.save('lead_contacts',{id:c.id,ai_visibility:'hidden'});assert.throws(()=>leadCommand(f,['contact',JSON.stringify({id:c.id,name:c.name,url:c.url})]),/existing visible/);
});
