import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {Store} from '../core/records/store.mjs';import {QueryService} from '../core/query.mjs';import {Domains} from '../core/domains.mjs';
function fixture(){const store=new Store(fs.mkdtempSync(path.join(os.tmpdir(),'godspeed-lead-command-'))),query=new QueryService(store),domains=new Domains(query,{provider:async()=>{throw Error('Explicit commands must not request a generated acknowledgement');}});let n=0;return {store,query,run:(message,request_id='fictional-'+n++)=>domains.invoke('conversation-chat',{conversation_id:'fictional-lead-command',request_id,message})};}
test('adopting a public position requires its selected visible adopted goal',async()=>{
 const f=fixture(),goal=f.store.save('goals',{title:'Fictional public work',status:'provisional'}),input={title:'Fictional source-aware position',status:'adopted',goal_id:goal.id};
 await assert.rejects(f.run('/lead position '+JSON.stringify(input)),/existing adopted goal/);assert.equal(f.store.list('lead_positions').length,0);
 f.store.save('goals',{id:goal.id,status:'adopted'});await f.run('/lead position '+JSON.stringify(input));const position=f.store.list('lead_positions')[0];assert.equal(position.goal_id,goal.id);
 await f.run('/lead position '+JSON.stringify({...input,id:position.id,status:'paused'}));assert.equal(f.store.get('lead_positions',position.id).status,'paused');
});
test('explicit lead commands preserve exact JSON strings and retries create no second example',async()=>{const f=fixture();assert.match((await f.run('/lead help')).reply,/never publish/);const content='A fictional reader asks: "When did this change?"\nPreserve the source’s actual words.',message='/lead example '+JSON.stringify({status:'approved',content});const first=await f.run(message,'same-request'),again=await f.run(message,'same-request');assert.deepEqual(again,first);assert.equal(f.store.list('lead_examples').length,1);assert.equal(f.store.list('lead_examples')[0].content,content);});
test('source selection excludes hidden notes and reported posts remain unverified',async()=>{const f=fixture(),hidden=f.store.save('notes',{title:'Fictional hidden work',content:'Private',ai_visibility:'hidden'});await assert.rejects(f.run('/lead source '+hidden.id+' on'),/assistant-visible/);const note=f.store.save('notes',{title:'Fictional selected work',content:'Source'});await f.run('/lead source '+note.id+' on');assert.equal(f.store.get('notes',note.id).lead_evidence,true);const entry=f.store.save('lead_entries',{title:'Fictional draft',status:'ready'});await f.run('/lead outcome '+entry.id+' '+JSON.stringify({status:'posted',posted_url:'https://example.invalid/fictional-post',posted_at:'2026-01-01T12:00:00Z'}));assert.equal(f.store.get('lead_entries',entry.id).posted_verification.state,'unverified');assert.equal(f.store.list('notifications').length,0);});
test('lead configuration rejects credentials and preserves the selected public profile',async()=>{const f=fixture();await assert.rejects(f.run('/lead configure '+JSON.stringify({profile_urls:['https://example.invalid?api_key=fictional-secret']})),/without credentials/);assert.equal(f.store.get('settings','lead'),undefined);await f.run('/lead configure '+JSON.stringify({profile_urls:['https://example.invalid/public-profile']}));assert.deepEqual(f.store.get('settings','lead').profile_urls,['https://example.invalid/public-profile']);});
