import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import http from 'node:http';
import {Store} from '../core/records/store.mjs';import {QueryService} from '../core/query.mjs';import {procedure as rawProcedure} from '../core/procedures.mjs';
const procedure=(job,context)=>rawProcedure(job,{...context,provider:async input=>input.kind==='lead-verification'?{passed:true,reason:'Fictional exact claims and reader checked'}:context.provider(input)});
function fixture(){const store=new Store(fs.mkdtempSync(path.join(os.tmpdir(),'godspeed-lead-'))),query=new QueryService(store);store.save('profiles',{timezone:'Europe/Berlin'});const goal=store.save('goals',{title:'Fictional useful public contributions',status:'adopted'});const position=store.save('lead_positions',{title:'Fictional source-aware tools',status:'adopted',goal_id:goal.id});store.save('lead_examples',{status:'approved',content:'A source date can save a surprisingly long argument.'});const source=store.save('notes',{title:'Fictional actual work',content:'The fictional adapter preserves dated source claims.',lead_evidence:true});return {store,query,position,source,goal};}
function entry(f){return {kind:'entry',title:'Fictional source dates',position_id:f.position.id,shape:'post',options:[{text:'A source date helps explain which remembered fact still applies.',lighthearted:false},{text:'My fictional adapter now remembers when its facts stopped being facts.',lighthearted:true},{text:'Keeping a source date makes an old answer easier to question.',lighthearted:false}],evidence:[{source_id:f.source.id,quote:'preserves dated source claims.'}],reader_check:{reader:'People who use saved notes',venue:'A public conversation',understands:'Old and current facts differ',feels:'Curious',takeaway:'Check the date',spam_check:'Offers a useful observation'},reach:null};}
test('an unrelated adopted goal cannot authorize public drafts for an unlinked or paused goal',async()=>{
 const f=fixture();f.store.save('goals',{title:'Fictional unrelated home task',status:'adopted'});f.store.save('goals',{id:f.goal.id,status:'paused'});
 const provider=async()=>{throw Error('A paused linked goal must not generate any draft');};
 const paused=await procedure({kind:'lead',id:'fictional-paused-goal'},{...f,provider});assert.equal(paused.silent,true);assert.match(paused.reason,/linked to an adopted goal/);
 f.store.save('lead_positions',{id:f.position.id,goal_id:null});const unlinked=await procedure({kind:'lead',id:'fictional-unlinked-goal'},{...f,provider});assert.equal(unlinked.silent,true);assert.equal(f.store.list('lead_entries').length,0);
});
test('pausing a linked goal during drafting prevents delivery and retains the failed run',async()=>{
 const f=fixture();await assert.rejects(procedure({kind:'lead',id:'fictional-goal-change'},{...f,provider:async()=>{f.store.save('goals',{id:f.goal.id,status:'paused'});return entry(f);}}),/changed during drafting/);
 assert.equal(f.store.list('lead_entries').length,0);assert.equal(f.store.list('notifications').length,0);assert.ok(f.store.list('lead_runs').some(r=>r.state==='failed'));
});
test('lead keeps one complete draft per local day and records actual outcomes without publishing',async()=>{const f=fixture();let calls=0;const provider=async x=>{calls++;assert.equal(x.context.workflow.name,'lead');assert.deepEqual(x.context.outcomes,[]);return entry(f);};const result=await procedure({kind:'lead',id:'fictional-lead'},{...f,provider});assert.equal(f.store.get('lead_entries',result.entry_id).status,'ready');assert.equal(f.store.get('notes',result.record_id).content.split('\n\n').length,3);assert.equal(f.store.list('notifications').length,1);const again=await procedure({kind:'lead',id:'a-different-routine'},{...f,provider});assert.equal(again.silent,true);assert.equal(calls,1);assert.equal(f.store.list('lead_entries').length,1);assert.equal(f.store.list('lead_runs').length,2);});
test('lead refuses invented evidence after one correction and retains the failed run',async()=>{const f=fixture();let calls=0;await assert.rejects(procedure({kind:'lead',id:'fictional-lead'},{...f,provider:async()=>{calls++;return {...entry(f),evidence:[{source_id:f.source.id,quote:'An invented customer success'}]};}}),/after one correction/);assert.equal(calls,2);assert.equal(f.store.list('lead_entries').length,0);assert.equal(f.store.list('notifications').length,0);assert.ok(f.store.list('lead_runs').some(r=>r.state==='failed'));});
test('five unposted entries trigger a retained redraft instead of a sixth entry',async()=>{const f=fixture();const originals=[];for(let n=0;n<5;n++)originals.push(f.store.save('lead_entries',{title:'Fictional old draft '+n,status:'ready',position_id:f.position.id,shape:'post',content:'Original retained words '+n,delivery_day:'2026-01-0'+(n+1)}));const result=await procedure({kind:'lead',id:'fictional-redraft'},{...f,provider:async x=>{assert.equal(x.context.redraft.id,originals[0].id);return entry(f);}});assert.equal(result.entry_id,originals[0].id);assert.equal(f.store.list('lead_entries').length,5);assert.ok(f.store.list('record_history').some(r=>r.source_id===originals[0].id&&r.snapshot.content==='Original retained words 0'));});
test('a shape shown four times without an actual post stays closed',async()=>{const f=fixture();for(let n=0;n<4;n++)f.store.save('lead_entries',{status:'shown',shape:'post',position_id:f.position.id,shown_at:new Date().toISOString(),delivery_day:'2026-01-0'+(n+1)});await assert.rejects(procedure({kind:'lead',id:'fictional-blocked'},{...f,provider:async x=>{assert.ok(x.context.blocked_shapes.some(b=>b.shape==='post'));return entry(f);}}),/closed by actual outcomes/);assert.equal(f.store.list('lead_entries').length,4);});
test('due research precedes content and is not marked completed by saving an action',async()=>{const f=fixture();f.store.save('lead_positions',{id:f.position.id,research_due_at:'2026-01-01T00:00:00Z',research_action:'Inspect the fictional dated-claim result'});const result=await procedure({kind:'lead',id:'fictional-research'},{...f,provider:async x=>{assert.equal(x.context.research_priority.id,f.position.id);return {kind:'research',title:'Inspect fictional source dates',position_id:f.position.id,action:'Read the actual dated-claim result before preparing another post.',evidence:entry(f).evidence,reader_check:entry(f).reader_check};}});assert.equal(f.store.get('lead_entries',result.entry_id).kind,'research');assert.equal(f.store.get('lead_positions',f.position.id).research_completed_at,undefined);});
test('contact rotation reads actual bytes and advances once per day, including quiet days',async t=>{const f=fixture(),server=http.createServer((req,res)=>res.end('Fictional recent statement '+req.url));await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));for(let n=0;n<17;n++)f.store.save('lead_contacts',{name:'Fictional contact '+n,url:'http://127.0.0.1:'+server.address().port+'/'+n});let seen=[];const provider=async x=>{seen.push(x.context.contacts.map(c=>c.name));assert.equal(x.context.sources.length,15);assert.ok(x.context.sources.every(s=>s.content.includes('Fictional recent statement')));return {kind:'quiet',reason:'No useful opening in the actually read statements'};};await procedure({kind:'lead',id:'fictional-rotation'},{...f,provider});await procedure({kind:'lead',id:'fictional-rotation'},{...f,provider});assert.deepEqual(seen[0],seen[1]);for(const run of f.store.list('lead_runs'))f.store.save('lead_runs',{id:run.id,local_day:'2026-01-01'});await procedure({kind:'lead',id:'fictional-rotation'},{...f,provider});assert.notDeepEqual(seen[1],seen[2]);assert.equal(f.store.list('notifications').length,0);assert.equal(f.store.list('watch_observations').length,45);});
test('overlapping provider calls cannot create two daily contributions',async()=>{const f=fixture();let count=0,release;const both=new Promise(r=>release=r);const provider=async()=>{if(++count===2)release();await both;return entry(f);};const results=await Promise.all([procedure({kind:'lead',id:'one'},{...f,provider}),procedure({kind:'lead',id:'two'},{...f,provider})]);assert.equal(results.filter(r=>r.record_id).length,1);assert.equal(f.store.list('lead_entries').length,1);assert.equal(f.store.list('notifications').length,1);});
test('without approved examples lead records a quiet reason before calling any model',async()=>{const f=fixture();for(const e of f.store.list('lead_examples'))f.store.save('lead_examples',{id:e.id,status:'refused'});const result=await procedure({kind:'lead',id:'fictional-unconfigured'},{...f,provider:async()=>{throw Error('No approved example must not generate a draft');}});assert.equal(result.silent,true);assert.match(f.store.list('lead_runs')[0].content,/No approved writing examples/);});
test('a matching quote cannot bypass the separate factual and reader check',async()=>{const f=fixture();let writes=0,checks=0;await assert.rejects(rawProcedure({kind:'lead',id:'fictional-rejected-claim'},{...f,provider:async input=>{if(input.kind==='lead-verification'){checks++;return {passed:false,reason:'The draft inflates the actual source result'};}writes++;return entry(f);}}),/inflates/);assert.equal(writes,2);assert.equal(checks,2);assert.equal(f.store.list('lead_entries').length,0);assert.equal(f.store.list('job_receipts').filter(r=>r.kind==='lead-verification'&&r.state==='failed').length,2);});
test('a reported publication counts only after reading its actual matching public text',async t=>{const f=fixture(),text=entry(f).options[0].text,server=http.createServer((req,res)=>res.end('<article>'+text+'</article>'));await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));const posted=f.store.save('lead_entries',{...entry(f),status:'posted',posted_at:new Date().toISOString(),posted_url:'http://127.0.0.1:'+server.address().port,posted_verification:{state:'unverified'},delivery_day:'2026-01-01'});await procedure({kind:'lead',id:'fictional-post-readback'},{...f,provider:async input=>{const observed=input.context.outcomes.find(e=>e.id===posted.id);assert.equal(observed.posted_verification.state,'verified');return {kind:'quiet',reason:'The actual posted contribution is enough for now'};}});const saved=f.store.get('lead_entries',posted.id);assert.equal(saved.posted_verification.quote,text);assert.ok(f.store.get('watch_observations',saved.posted_verification.observation_id).content.includes(text));assert.equal(f.store.list('notifications').length,0);});
