import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import http from 'node:http';
import {Store} from '../core/records/store.mjs';import {QueryService} from '../core/query.mjs';import {procedure} from '../core/procedures.mjs';
// Its sources are local fixture servers, which the product itself refuses to read (core/outbound-fetch.mjs).
process.env.GODSPEED_OUTBOUND_ALLOW_LOCAL='1';
async function fixture(t){const server=http.createServer((req,res)=>{res.writeHead(200,{'content-type':'text/plain'});res.end('Fictional primary release: retrieval now preserves dated source claims.');});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));const store=new Store(fs.mkdtempSync(path.join(os.tmpdir(),'godspeed-radar-'))),query=new QueryService(store);store.save('watch_topics',{title:'Fictional personal AI releases',radar:true,url:'http://127.0.0.1:'+server.address().port});return {store,query};}
const proposal=s=>({kind:'proposal',title:'Preserve dated retrieval sources',change:'Add source dates to the local retrieval result',benefit:'Test whether historical claims remain distinguishable',cost:'One local adapter change',experiment:'Run the fictional current and historical claim queries',check:'Both exact source dates remain visible',rollback:'Restore the retained adapter version',end_date:'2026-12-01',source_id:s.id,quote:'retrieval now preserves dated source claims.',verdict:null});
test('overlapping radar runs retain one stable proposal and one alert for the same local change',async t=>{
 const f=await fixture(t);let calls=0,release;const both=new Promise(r=>release=r),provider=async input=>{if(++calls===2)release();await both;return proposal(input.context.sources[0]);};
 const results=await Promise.all([procedure({id:'one',kind:'radar'},{...f,provider}),procedure({id:'two',kind:'radar'},{...f,provider})]);
 assert.equal(results.filter(r=>r.record_id).length,1);assert.equal(results.filter(r=>r.silent).length,1);assert.equal(f.store.list('notes').filter(n=>n.source_app==='radar').length,1);assert.equal(f.store.list('notifications').length,1);assert.equal(f.store.list('watch_runs').length,2);
});
test('radar fetches current source bytes and retains one quoted proposal with an empty user verdict',async t=>{const f=await fixture(t);let calls=0;const provider=async x=>{calls++;assert.equal(x.context.workflow.name,'mc-radar');return proposal(x.context.sources[0]);};const result=await procedure({id:'fictional-radar',kind:'radar'},{...f,provider}),note=f.store.get('notes',result.record_id);assert.equal(note.radar.verdict,null);assert.equal(note.radar.quote,'retrieval now preserves dated source claims.');assert.ok(note.radar.source_observation_id);assert.equal(f.store.list('watch_runs').length,1);const again=await procedure({id:'fictional-radar',kind:'radar'},{...f,provider});assert.equal(again.silent,true);assert.equal(calls,1);assert.equal(f.store.list('notes').filter(n=>n.source_app==='radar').length,1);});
test('radar refuses a fabricated quote after one correction and retains failure rather than a proposal',async t=>{const f=await fixture(t);let calls=0;const provider=async x=>{calls++;return {...proposal(x.context.sources[0]),quote:'Invented source result'};};await assert.rejects(procedure({id:'fictional-radar',kind:'radar'},{...f,provider}),/after one correction/);assert.equal(calls,2);assert.equal(f.store.list('notes').filter(n=>n.source_app==='radar').length,0);assert.ok(f.store.list('watch_runs').some(r=>r.state==='failed'));});
test('radar cannot choose its own verdict or manufacture an improvement from missing sources',async()=>{const store=new Store(fs.mkdtempSync(path.join(os.tmpdir(),'godspeed-radar-'))),query=new QueryService(store);let calls=0;const result=await procedure({id:'fictional-radar',kind:'radar'},{store,query,provider:async()=>{calls++;return {kind:'proposal',verdict:'Adopt'};}});assert.equal(result.silent,true);assert.equal(calls,0);assert.equal(store.list('notes').length,0);assert.match(store.list('watch_runs')[0].content,/No configured/);});
test('three blind source runs create one warning and later blind repeats stay quiet',async()=>{const store=new Store(fs.mkdtempSync(path.join(os.tmpdir(),'godspeed-radar-'))),query=new QueryService(store);store.save('watch_topics',{radar:true,title:'Fictional unreachable source',url:'http://127.0.0.1:1'});for(let i=0;i<4;i++)await procedure({id:'fictional-radar',kind:'radar'},{store,query,provider:async()=>{throw Error('No source must reach the model');}});assert.equal(store.list('watch_runs').length,4);assert.equal(store.list('notifications').length,1);assert.match(store.list('notifications')[0].body,/three/);});
test('radar rejects credential-bearing URLs without copying values into its run log',async()=>{const store=new Store(fs.mkdtempSync(path.join(os.tmpdir(),'godspeed-radar-'))),query=new QueryService(store);store.save('watch_topics',{radar:true,url:'https://fictional-user:fictional-secret@example.invalid/releases?api_key=fictional-token'});await procedure({id:'fictional-radar',kind:'radar'},{store,query,provider:async()=>{throw Error('Credential-bearing sources must not reach the model');}});const log=JSON.stringify(store.list('watch_runs'));assert.ok(!log.includes('fictional-secret'));assert.ok(!log.includes('fictional-token'));});
