import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {Store} from '../core/records/store.mjs';import {QueryService} from '../core/query.mjs';import {Domains} from '../core/domains.mjs';
import {procedure} from '../core/procedures.mjs';
test('subscription meter distinguishes unreadable plans, unpriced tokens and actual cumulative spend',async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'godspeed-subs-')),store=new Store(root),domains=new Domains(new QueryService(store));
 fs.mkdirSync(path.join(root,'profile'));fs.mkdirSync(path.join(root,'.godspeed','usage'),{recursive:true});
 fs.writeFileSync(path.join(root,'profile','subscriptions.md'),'## Fictional flat plan\nCosts: $20 per month\nReceipts: none\n\n## Fictional metered plan\nReceipts: openrouter\n');
 const ledger=path.join(root,'.godspeed','usage','fictional-router.jsonl'),at=new Date().toISOString();
 fs.writeFileSync(ledger,JSON.stringify({at,usage_total_usd:5})+'\n'+JSON.stringify({at,usage_total_usd:7})+'\n');
 fs.writeFileSync(path.join(root,'.godspeed','subscription-receipts.json'),JSON.stringify({openrouter_ledger:ledger}));
 const run=args=>domains.invoke('personal-operation',{type:'subscription-command',args});
 const measured=JSON.parse((await run(['meter','--json','--no-network'])).result);
 assert.equal(measured.subscriptions[0].measured,false);assert.equal(measured.subscriptions[0].valueUsd,null);
 assert.equal(measured.subscriptions[1].meteredUsd,2);
 const transcripts=path.join(root,'.godspeed/fictional-transcripts');fs.mkdirSync(transcripts);
 fs.writeFileSync(path.join(root,'.godspeed/subscription-receipts.json'),JSON.stringify({openrouter_ledger:ledger,claude_projects:[transcripts]}));
 await run(['set','Fictional token plan','--field','receipts','--value','claude-code']);
 const absent=JSON.parse((await run(['meter','--json','--no-network'])).result).subscriptions.find(s=>s.name==='Fictional token plan');assert.equal(absent.measured,false);
 fs.writeFileSync(path.join(transcripts,'fictional.jsonl'),JSON.stringify({timestamp:at,message:{model:'fictional/unpriced',usage:{input_tokens:5,output_tokens:7}}})+'\n');
 const unpriced=JSON.parse((await run(['meter','--json','--no-network'])).result).subscriptions.find(s=>s.name==='Fictional token plan');assert.equal(unpriced.measured,true);assert.equal(unpriced.models[0].priced,false);assert.equal(unpriced.valueUsd,null);
 fs.appendFileSync(path.join(transcripts,'fictional.jsonl'),'{"usage":broken}\n');
 const broken=JSON.parse((await run(['meter','--json','--no-network'])).result).subscriptions.find(s=>s.name==='Fictional token plan');assert.equal(broken.measured,false);assert.match(broken.why,/unreadable/);
 fs.writeFileSync(path.join(transcripts,'fictional.jsonl'),JSON.stringify({timestamp:'2000-01-01T00:00:00Z',message:{model:'fictional/unpriced',usage:{input_tokens:5}}})+'\n');
 const zero=JSON.parse((await run(['meter','--json','--no-network'])).result).subscriptions.find(s=>s.name==='Fictional token plan');assert.equal(zero.measured,true);assert.equal(zero.valueUsd,0);
 assert.match((await run(['help'])).result,/mc-subs/);
 await assert.rejects(run(['dashboard','--out','../outside.md','--no-network']),/inside|review/);
 await run(['dashboard','--out','observations/subscription-reviews/fictional.md','--no-network']);
 assert.equal(fs.existsSync(path.join(root,'observations/subscription-reviews/fictional.md')),true);
 const command=await domains.invoke('conversation-chat',{conversation_id:'fictional-subs',request_id:'fictional-register',message:'/subs register --json'});
 assert.equal(JSON.parse(command.reply).subs.length,3);
 await run(['set','Fictional flat plan','--field','renews','--value','The first of each month']);
 const updated=JSON.parse((await run(['register','--json'])).result);
 assert.equal(updated.subs[0].costUsd,20);assert.equal(updated.subs[0].renews,'The first of each month');
 const historyCount=fs.readdirSync(path.join(root,'profile/subscription-history')).length;assert.equal(historyCount,2);
 await run(['set','Fictional flat plan','--field','renews','--value','The first of each month']);
 assert.equal(fs.readdirSync(path.join(root,'profile/subscription-history')).length,historyCount);
 await assert.rejects(run(['set','Fictional flat plan','--field','costs','--value','20\nNew field: lie']),/single-line/);
 const query=new QueryService(store),job={kind:'subscription-review',no_network:true};
 const review=await procedure(job,{store,query}),saved=store.get('notes',review.record_id);assert.equal(review.verified,true);assert.match(saved.content,/Fictional metered plan/);assert.equal(saved.measurement.rows.find(r=>r.name==='Fictional metered plan').meteredUsd,2);
 assert.equal((await procedure(job,{store,query})).silent,true);assert.equal(store.list('notifications').length,1);
 fs.appendFileSync(ledger,JSON.stringify({at,usage_total_usd:8})+'\n');assert.equal((await procedure(job,{store,query})).silent,undefined);assert.equal(store.list('notifications').length,2);
});
